# Generated by Django 4.2.7 on 2024-03-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField(null=True)),
                ('match_timestamp', models.IntegerField(null=True)),
                ('match_periods_first', models.CharField(max_length=250, null=True)),
                ('match_periods_second', models.CharField(max_length=250, null=True)),
                ('match_venue_name', models.CharField(max_length=250, null=True)),
                ('match_venue_city', models.CharField(max_length=250, null=True)),
                ('match_status_long', models.CharField(max_length=250, null=True)),
                ('league_id', models.CharField(max_length=250, null=True)),
                ('league_name', models.CharField(max_length=100, null=True)),
                ('league_country', models.CharField(max_length=250, null=True)),
                ('league_logo', models.URLField(max_length=250, null=True)),
                ('league_flag', models.URLField(max_length=250, null=True)),
                ('league_season', models.IntegerField(null=True)),
                ('league_round', models.CharField(max_length=100, null=True)),
                ('home_team_name', models.CharField(max_length=250, null=True)),
                ('home_team_logo', models.URLField(max_length=250, null=True)),
                ('home_team_winner', models.CharField(max_length=250, null=True)),
                ('away_team_name', models.CharField(max_length=250, null=True)),
                ('away_team_logo', models.URLField(max_length=25, null=True)),
                ('away_team_winner', models.CharField(max_length=250, null=True)),
                ('home_team_goals', models.IntegerField(null=True)),
                ('away_team_goals', models.IntegerField(null=True)),
                ('halftime_score', models.CharField(max_length=250, null=True)),
                ('extratime_score', models.CharField(max_length=250, null=True)),
                ('penalty_score', models.CharField(max_length=250, null=True)),
                ('match_refree', models.CharField(blank=True, max_length=250, null=True)),
                ('fulltime_score', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
