# Generated by Django 4.2.7 on 2024-03-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_team_logo',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
